### ISSUE TITLE
Column filters don't work

### ISSUE THREAD

**Issue by anyweez** [revolist/revogrid#635]
**Describe the issue**
Clicking the filter icon on any column doesn't display the expected UI element, and prints an error to the console instead. This is occurring in the official demo as well: https://rv-grid.com/demo.

Stack trace from console:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at FilterPanel.getFilterItemsList (filter.panel.tsx:138:1)
    at FilterPanel.render (filter.panel.tsx:461:1)
    at callRender (index.js:1802:1)
    at updateComponent (index.js:1762:1)
    at index.js:1739:1
    at enqueue (index.js:1744:1)
    at dispatchHooks (index.js:1739:1)
    at Array.dispatch (index.js:1687:1)
    at consume (index.js:261:1)
    at flush (index.js:271:1) <revogr-filter-panel class=​"hydrated" style=​"display:​ none;​">​…​</revogr-filter-panel>​
consoleError @ index.js:52
callRender @ index.js:1824
updateComponent @ index.js:1762
(anonymous) @ index.js:1739
enqueue @ index.js:1744
dispatchHooks @ index.js:1739
dispatch @ index.js:1687
consume @ index.js:261
flush @ index.js:271
```

Simple React component that reproduces the issue on v4.10.29:

```tsx
import React from 'react';
import { ColumnRegular, RevoGrid } from '@revolist/react-datagrid';

function App() {
  const [events, setEvents] = React.useState<SampleEvent[]>([]);

  const columns: ColumnRegular[] = [
    {
      prop: 'timestamp',
      name: 'Timestamp',
      size: 250,
      filter: false,
    },
    {
      prop: 'summary',
      name: 'Summary',
      size: 360,
      filter: false,
    },
    {
      prop: 'actor',
      name: 'Actor',
      filter: 'string',
    },
    {
      prop: 'target',
      name: 'Target',
      filter: 'string',
    },
    {
      prop: 'type',
      name: 'Event type',
      filter: 'string',
    },
  ];

  return (
    <div style={{ height: '100%' }} className="App">
      <RevoGrid 
        columns={columns} 
        source={events} 
        rowSize={32} 
        filter={true}  />
    </div>
  );
}
```

**Comment by revolist** [comment]
Fixed, was connected with filter plugin improvement.
Please get the latest
